USE Lab3_DBMS
GO

INSERT INTO Store VALUES (99, 'Str. Avram Iancu', 100)
ALTER DATABASE Lab3_DBMS SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Store SET address = 'new1' WHERE id = 99
WAITFOR DELAY '00:00:05'
COMMIT TRAN

--ALTER DATABASE Lab3_DBMS SET ALLOW_SNAPSHOT_ISOLATION OFF
