version: '3'
services:
  db:
    build: "./db_docker/"
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  backend:
    build: .
    environment:
      PORT: "${PORT}"
      SOCKET_PORT: "${SOCKET_PORT}"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
      - "8081:8081"